### ISSUE TITLE
Share Wall Design

### ISSUE THREAD

**Issue by luke-** [humhub/sharebetween#17]
![share2](https://user-images.githubusercontent.com/4736168/222537338-6b7a068f-0700-45b8-951c-5c62f436cd43.png)
![share1](https://user-images.githubusercontent.com/4736168/222537340-5d6fed51-2937-4a1f-9712-4d51a5318b77.png)

**Comment by samuk** [comment]
This is quite timely, I was just investigating this functionality.

How are you thinking of handling comments on shared posts? We were thinking of not allowing them on child posts & redirecting users to make comments on the original parent post.

**Comment by luke-** [comment]
For now, the plan is to always display the comments/links of the shared post.

**Comment by funkycram** [comment]
@luke- Thanks for developing this promising module!
Would you accept a PR from myself allowing to have a setting to disable addons in the stream entry footer, such as comments and likes?

Then, we would have a the variable `$disableAddons` sent in the view https://github.com/humhub/sharebetween/blob/master/widgets/views/wall-entry.php and the 2 last lines would be replaced with:

```php
$streamEntryOptions = new \humhub\modules\content\widgets\stream\WallStreamEntryOptions();
$streamEntryOptions->disableAddons = $disableAddons;
?>
<?= StreamEntryWidget::renderStreamEntry($share->getContentRecord(), $streamEntryOptions); ?>
```

This setting could be a new property in the `Module` class.
Thanks!

**Comment by luke-** [comment]
@funkycram Currently, the idea is to display only show the addons of the shared content. The share itself should not have its own comments / likes etc. at the moment.

Thats your plan with the option right?

Of course, in the future we can still make the behavior configurable. But as described would be the easiest way for now.

**Comment by funkycram** [comment]
@luke- Sorry, I was unclear. The goal is to have the possibility to hide the addons (comments, likes, ...) on the embeded content. The share itself should always have addons disabled (which is not the case actually, but I understand in you last comment that it's planned).

@samuk Am I right?

![image](https://user-images.githubusercontent.com/23310825/224532378-44aa480f-1c69-4ad4-b5df-1b4413343380.png)

![image](https://user-images.githubusercontent.com/23310825/224532719-2dc40e48-1e79-4d9a-ad01-dfebaf6d2ff8.png)

This would be the code of https://github.com/humhub/sharebetween/blob/master/widgets/views/wall-entry.php: 
```php
/** @var $disableSharedContentAddons bool */

$streamEntryOptions = new \humhub\modules\content\widgets\stream\WallStreamEntryOptions();
$streamEntryOptions->disableAddons = $disableSharedContentAddons;
?>
<?= StreamEntryWidget::renderStreamEntry($share->getContentRecord(), $streamEntryOptions); ?>

<?php if ($disableSharedContentAddons): ?>
    <?= \humhub\widgets\Button::info('View original content to comment and like') ?>
<?php endif ?>
```

In an ideally world, we would have a third possibility, to display addons, the comments are locked, only on the shared content:
![image](https://user-images.githubusercontent.com/23310825/224533026-48c89fc3-00a7-4e5c-844b-2fafbcca7680.png)

But I haven't find an easy way to do this.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/sharebetween/pull/22:

![share_post](https://user-images.githubusercontent.com/6995524/225103242-ea03fa58-d86a-4d11-a21c-889a30993a38.png)

![share_event](https://user-images.githubusercontent.com/6995524/225103247-f451a647-9fcd-46cd-a9e4-8f6c679df43b.png)
