### ISSUE TITLE
Current Situation of the share feature

### ISSUE THREAD

**Issue by vipul1994** [humhub/sharebetween#2]
Hey, 
Just wanted to know the current status of share feature on humhub and what else need to be done. So I can contribute on this repository.
Thanks.

**Comment by cebe** [comment]
You can install it and try it out in your humhub installation. Basic sharing functionality is already working.

**Comment by vipul1994** [comment]
Can you add a brief readme to add this module in humhub

**Comment by cebe** [comment]
go to your humhub installation folder,

```
cd protected/modules
git clone https://github.com/humhub/humhub-modules-sharebetween sharebetween
```

after that it should show up in admin -> modules where you can click "install"

**Comment by vipul1994** [comment]
Thanks a lot for this.
Btw getting an error


Error: Call to a member function getPolymorphicRelation() on null in /var/www/html/humhub/protected/humhub/modules/sharebetween_share/widgets/views/streamEntry.php:1
Stack trace:
#0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require()
#1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/html/h...', Array)
#2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/html/h...', Array, Object(humhub\modules\sharebetween\widgets\StreamEntry))
#3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(192): yii\base\View->render('streamEntry', Array, Object(humhub\modules\sharebetween\widgets\StreamEntry))
#4 /var/www/html/humhub/protected/humhub/modules/sharebetween_share/widgets/StreamEntry.php(17): yii\base\Widget->render('streamEntry', Array)
#5 /var/www/html/humhub/protected/humhub/modules/content/widgets/WallEntry.php(109): humhub\modules\sharebetween\widgets\StreamEntry->run()
#6 /var/www/html/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(124): humhub\modules\content\widgets\WallEntry->renderWallEntry()
#7 /var/www/html/humhub/protected/humhub/modules/content/components/actions/Stream.php(259): humhub\modules\content\components\ContentActiveRecord->getWallOut()
#8 [internal function]: humhub\modules\content\components\actions\Stream->run()
#9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)
#10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array)
#11 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array)
#12 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/profile/st...', Array)
#13 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))
#14 /var/www/html/humhub/index.php(25): yii\base\Application->run()
#15 {main}

**Comment by vipul1994** [comment]
It worked finally. 
Few problem were like 
1. No method $content->canView() in ShareController.php.
2. Content does not have contentcontainer_id in its table. gave error in content.contentcontainer_id @ Share.php
3.     public $wallEntryLayout = "@sharebetween/widgets/views/wallEntry.php"; was not working in StreamEntry.php . Resolved by making it
           public $wallEntryLayout = "wallEntry.php";

Thanks for the module though. :)
