### ISSUE TITLE
Hide share link for private content

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/sharebetween#21]
I see here https://github.com/humhub/sharebetween/blob/master/services/ShareService.php#L67 `canCreate()` always returns `false` for not public content, so it would be good to hide the "Share" link completely for not public content, also don't allow to load the modal window, otherwise it is not clear why after submit the Share form we don't see any message about result like "Shared" or "Not shared".

**Comment by funkycram** [comment]
+1
We also need to handle the case where the content was public and shared and later turned to private.
Thanks!

**Comment by luke-** [comment]
@yurabakhtin Good point, can you please implemented that as suggested.

In case of @funkycram scenario, I would suggest  to show a message "You don't have access to this content." e.g. instead of the shared content .

**Comment by luke-** [comment]
+ Tests would be great for both possibiltiies...

**Comment by yurabakhtin** [comment]
@luke- I have done to hide the "Share" link for all private contents, also if content was changed to Private and current user has no permission to view it then it will looks like this:

![shared-no-access](https://user-images.githubusercontent.com/6995524/225226589-39aea4ea-cbcf-4f79-8c06-21dc95b713f1.png)
(Please note in new design it will looks with light yellow background)

> - Tests would be great for both possibiltiies...

Tests will be done for the ticket https://github.com/humhub/sharebetween/issues/18

**Comment by luke-** [comment]
@Semir1212 What kind of text should we display here when the content is no longer visible. 

I know something like that from FB: The content is no longer available. Either it has been deleted or is no longer available.

From a UI standpoint, it would probably be nice to have a heading in bold and then a 1-2 line explanation.

**Comment by Semir1212** [comment]
@luke- @yurabakhtin 

Content not available

This content has either been deleted or you no longer have permission to access it.

**Comment by yurabakhtin** [comment]
@luke- Done in commit https://github.com/humhub/sharebetween/pull/23/commits/9445e9aca32e7c5f9b1ab5442d475721389cd403.
