### ISSUE TITLE
Constant `Content::EVENT_SOFT_DELETE` does not exist

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/sharebetween#26]
`humhub\modules\content\models\Content::EVENT_SOFT_DELETE` used in 

https://github.com/humhub/sharebetween/blob/b8edd63c601c304ac3c3890bdbb04a857fb62eee/config.php#L12

seems not to exist. Not in `develop` branch, nor in any other:
https://github.com/search?q=repo%3Ahumhub%2Fhumhub+EVENT_SOFT_DELETE&type=code

Also, would there not be the need for before and after events instead?

- `Content::EVENT_BEFORE_SOFT_DELETE`
- `Content::EVENT_AFTER_SOFT_DELETE`

**Comment by martin-rueegg** [comment]
Actually, The `const` exists locally after installing 1.14.beta-2 via updater. So I don't understand why I can't find it in the repository? Hence, the problem may be between my chair and my keyboard ...!

**Comment by luke-** [comment]
@martin-rueegg I found it here: https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/models/Content.php#L136
