### ISSUE TITLE
Share content to space it was created in

### ISSUE THREAD

**Issue by Semir1212** [humhub/sharebetween#27]
This should not be possible.

**Comment by yurabakhtin** [comment]
@Semir1212 @luke- Fixed in PR https://github.com/humhub/sharebetween/pull/30.

**Comment by luke-** [comment]
@yurabakhtin Thanks, let me know when I can merge it

**Comment by yurabakhtin** [comment]
@luke- Done, it can be merged, please note I also denied and hide the option "Share this content on your profile stream" from content from the current user profile:

![hide_profile_sharing](https://user-images.githubusercontent.com/6995524/229137914-c7d603d9-da5a-489d-b410-a5d8060b5fdb.png)
