### ISSUE TITLE
Software Screenshots Share Module

### ISSUE THREAD

**Issue by luke-** [humhub/sharebetween#32]

**Comment by Eladnarlea** [comment]
Gumo! :) Ich hab jetzt mal geschaut, aber es ist bei mir noch nicht aktiviert, oder?

**Comment by Eladnarlea** [comment]
<img width="1331" alt="Screenshot 2023-04-27 at 8 30 09 AM" src="https://user-images.githubusercontent.com/105652258/234778454-a314a688-382a-4ba3-afe3-2c1241b4b47f.png">
<img width="849" alt="Screenshot 2023-04-27 at 8 29 49 AM" src="https://user-images.githubusercontent.com/105652258/234778459-ba269472-e284-4ec5-9c69-8e588fd3b349.png">
<img width="1323" alt="Screenshot 2023-04-27 at 8 29 28 AM" src="https://user-images.githubusercontent.com/105652258/234778460-7f318ab2-f958-488a-b70f-9be607b1df61.png">
<img width="1314" alt="Screenshot 2023-04-27 at 8 29 04 AM" src="https://user-images.githubusercontent.com/105652258/234778467-2e9e3223-4638-41d4-8e2d-864cc13c6f68.png">
<img width="1329" alt="Screenshot 2023-04-27 at 8 27 54 AM" src="https://user-images.githubusercontent.com/105652258/234778470-a595884d-78a8-44c3-94ed-1fcfad741959.png">
<img width="837" alt="Screenshot 2023-04-27 at 8 13 35 AM" src="https://user-images.githubusercontent.com/105652258/234778475-feec70dd-490e-447f-910c-91a687dbc71f.png">

**Comment by luke-** [comment]
@Eladnarlea Thanks!
