### ISSUE TITLE
Not intuitive Share button

### ISSUE THREAD

**Issue by ghost** [humhub/sharebetween#4]
I just installed the modue but the share button is not in an intuitive place.

It could be perfect to be next to "comment" under the publication. I am sure is really simple to insert same button there but I have not idea how to do it.

Could you give me the code to insert in the needed file to add this button there?

Thank you very much.

**Comment by eddiepiazza** [comment]
Class pannel for correct place is **wall-entry-controls** but next to Comment button there is an other DIV with class **shareLinkContainer** for facebook tuitter....

Now I am between wallEntry.php and shareLink.pho to insert Share button there. But this is going out my skills...

Some recommendations ?

**Comment by moliata** [comment]
@eddiepiazza Did you have any look placing it near Like or Comment button, I am trying to do that now, but I am out of luck.

**Comment by eddiepiazza** [comment]
No, i didn t. But try using the console to explore the object and edit it.
it s just CSS I guess
