### ISSUE TITLE
Some texts are not translatable

### ISSUE THREAD

**Issue by funkycram** [humhub/sharebetween#44]
Missing `Yii::t('SharebetweenModule.base', '...')`

E.g. https://github.com/humhub/sharebetween/blob/master/models/ShareForm.php#L23-L32

And one text is not using the correct module: https://github.com/humhub/sharebetween/blob/master/views/share/index.php#L15

**Comment by funkycram** [comment]
Thanks @gevorgmansuryan !
@luke- new translations are not yet available on https://translate.humhub.org/translation/translate/index?moduleId=sharebetween&language=fr
Once available, I'll do french translations.
Thanks!

**Comment by luke-** [comment]
@funkycram Should be avaialble now on the translation service.

**Comment by funkycram** [comment]
Thanks! French translations done.
