### ISSUE TITLE
Disable possibility to share on the profile stream when "profileDisableStream" is true

### ISSUE THREAD

**Issue by funkycram** [humhub/sharebetween#45]
Step to reproduce:

1) In the `common.php` file, add this configuration:
```
        'user' => [
            'profileDisableStream' => true,
        ],
```

2)
![image](https://github.com/humhub/sharebetween/assets/23310825/e020b3e3-17e8-4e13-a3f5-a0b50843c5cb)

"Share this content on your profile stream" shouldn't be available.

**Comment by yurabakhtin** [comment]
@funkycram Thank you for the report!
@luke- Fixed in PR https://github.com/humhub/sharebetween/pull/46.

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
