### ISSUE TITLE
Add shared calendar events to destination Calendar

### ISSUE THREAD

**Issue by dantefromhell** [humhub/sharebetween#57]
When sharing a calendar event from Space A to Space B the calendar event is shown in the stream of Space B, but neither in the Calendar view on Space B nor the "Upcoming events" widget.

This makes it very easy for space members to miss an event they have been invited to and prevents the calendar event from being exported in a per-space ICS.

What would be the best approach to fix this issue?

**Comment by luke-** [comment]
Hmm, unfortunately this is complicated to implement. Currently, shared content is technically just a link.

It would probably be easiest if the calendar module took this "shared content" into account.

**Comment by dantefromhell** [comment]
@luke- 
If that's the best way forward I'm happy to open a new issue in the calendar module.

**Comment by dantefromhell** [comment]
✅ Done, I'm closing this issue in favar of https://github.com/humhub/calendar/issues/464
