### ISSUE TITLE
New Wording for Share Notification

### ISSUE THREAD

**Issue by mbumpalumpa** [humhub/sharebetween#67]
The current notification "`{$User}` created ." needs to be replaced with a new one "`{$User}` shared something interesting from Space `{$SpaceName}.`"

|X|Wording|
|-|-|
|Old|`{$User}` created .|
|New|`{$User}` shared something interesting from Space `{$SpaceName}`.|

**Ref:** https://github.com/humhub/sharebetween/issues/36

**Comment by luke-** [comment]
@mbumpalumpa Ok?

**Comment by yurabakhtin** [comment]
@mbumpalumpa @Semir1212 Commit https://github.com/humhub/sharebetween/pull/68/commits/7ce2b2554e0e9644ff89997646f4c60534e0125d.

I have detected the notification text is used as default:

![share-wording-bold](https://github.com/user-attachments/assets/f6cbed9a-6eba-4656-990b-9c0ee33a9a6f)

**Comment by yurabakhtin** [comment]
@mbumpalumpa Commit https://github.com/humhub/sharebetween/pull/68/commits/d83e22d85bb4f24987ff4330a86ef6f2d9988d8d:

![share-wording-notifications](https://github.com/user-attachments/assets/680265a5-1d26-4595-9c15-3aabe7cd0ff9)

**Comment by yurabakhtin** [comment]
@mbumpalumpa @luke- PR https://github.com/humhub/sharebetween/pull/69:

![share-user-dashboard-notifications](https://github.com/user-attachments/assets/c82e8e6e-ce15-4592-8122-d350edb3ee1b)

**Comment by luke-** [comment]
@mbumpalumpa Let me know when it's ready to merge & release.
